version: "3.7"

services:
  # frontend:
    # TODO: Thomas

  backend:
    image: node:14
    container_name: backrow-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - backrow-network
    depends_on:
      - database

  # proxy:
    # TODO: Marianne

  # admin:
  # TODO: Marianne


  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backrow
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - backrow-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: backrow-phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - backrow-network

networks:
  backrow-network:
    driver: bridge
