services:
  frontend:
    build:
      context: ./frontend
      target: production
    depends_on:
      - backend
    networks:
      - backrow-network
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    mem_limit: 256m
    cpu_shares: 512

  backend:
    build:
      context: ./backend
      target: production
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - backrow-network
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    mem_limit: 512m
    cpu_shares: 1024

  proxy:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backrow-network
    depends_on:
      - frontend
      - backend
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    mem_limit: 512m
    cpu_shares: 512

  database:
    image: mariadb:11
    restart: always
    environment:
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - backrow-network
    mem_limit: 2048m
    cpu_shares: 1024

networks:
  backrow-network:
    driver: bridge
