version: "3.7"

services:
  frontend:
    # TODO: Thomas

  backend:
    # TODO: Quentin

  proxy:
    # TODO: Marianne

  # admin:
  # TODO: Marianne

  database:
    # TODO: Quentin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: backrow-phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=database
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - backrow-network

networks:
  backrow-network:
    driver: bridge
