services:
  frontend:
    build:
      context: ./frontend
      target: production
    depends_on:
      - backend
    networks:
      - backrow-network
  backend:
    build:
      context: ./backend
      target: production
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - backrow-network

  proxy:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backrow-network
    depends_on:
      - frontend
      - backend

  database:
    image: mariadb:11
    restart: never
    environment:
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - backrow-network

networks:
  backrow-network:
    driver: bridge
